<script setup>
/* Copyright 2026 上海如静知华信息科技有限公司 */
import AppIcon from './AppIcon.vue';import {useAuthStore} from '../stores/auth';import {useRouter} from 'vue-router'
const props=defineProps({mode:{type:String,default:'admin'}});const auth=useAuthStore(),router=useRouter()
const shopfloor=[['/shopfloor','home','班组工作台'],['/shopfloor/report','report','生产报工'],['/shopfloor/tasks','order','工序任务'],['/shopfloor/material','box','物料领用'],['/shopfloor/quality','quality','质量自检'],['/shopfloor/andon','risk','异常呼叫']]
const admin=[['/admin','home','生产驾驶舱'],['/admin/work-orders','order','生产工单'],['/admin/schedule','calendar','计划排程'],['/admin/process','process','工艺路线'],['/admin/quality','quality','质量管理'],['/admin/equipment','machine','设备管理'],['/admin/material','box','物料追溯'],['/admin/report','chart','生产分析']]
const menus=props.mode==='shopfloor'?shopfloor:admin;function logout(){auth.logout();router.push('/login')}
</script>
<template><div class="app-shell" :class="`mode-${mode}`"><aside><div class="brand"><div class="brand-mark">ZH</div><div><b>知华 MES</b><small>制造执行系统</small></div></div><div class="line-card" v-if="mode==='shopfloor'"><span>当前工作中心</span><b>总装一线</b><small>早班 · 08:00—16:00</small></div><nav><router-link v-for="m in menus" :key="m[0]" :to="m[0]"><AppIcon :name="m[1]"/><span>{{m[2]}}</span><em v-if="m[2]==='异常呼叫'">1</em><em v-if="m[2]==='设备管理'">1</em></router-link></nav><div class="aside-foot"><span>社区源码版 · v1.0.0</span><a href="https://www.zhuatech.cn/" target="_blank">www.zhuatech.cn</a></div></aside><main><header><div><span class="workspace">{{mode==='shopfloor'?'装配车间 / 总装一线':'第一制造中心'}}</span><span class="period">生产日期 2026-07-29 · 周三</span></div><div class="header-actions"><span class="shift-live"><i></i> 数据刷新正常</span><button class="icon-button"><AppIcon name="bell"/><i></i></button><div class="avatar">{{auth.user?.fullName?.slice(0,1)|| (mode==='shopfloor'?'徐':'沈')}}</div><div class="user"><b>{{auth.user?.fullName|| (mode==='shopfloor'?'徐师傅':'沈清和')}}</b><small>{{mode==='shopfloor'?'装配班组长':'生产计划主管'}}</small></div><button class="logout" @click="logout">退出</button></div></header><section class="page"><slot/></section></main></div></template>
